[AT]
base = "app..."
domains_table = "tbl..."
accounts_table = "tbl..."
accounts_view = "viw..."
hosting_table = "tbl..."
token = "patm..."


[Servers]
proxy = ["176.9.0.2", "176.9.0.2"]
check_interval_sec = 30
timeout_sec = 5

